name: Test gameboy_emulator

on:
  push:
    paths-ignore:
      - '.github/**'
      - '.gitignore'

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-test-for-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up GCC
        uses: egor-tensin/setup-gcc@v1
        with:
          version: latest
          platform: x64
      - name: Set up dependencies
        run: |
          sudo apt-get install -y libxtst-dev libxdamage-dev libxfixes-dev libxrandr-dev libpam-dev libxinerama-dev libxcursor-dev
          sudo apt install libwayland-dev libxkbcommon-dev xorg-dev
      - name: Run tests
        run: cargo test --verbose
